sudo: required
language: go
dist: xenial

go:
  - 1.13.4

before_script:
  - if [ "$DOCKER_USERNAME" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - ./install-operator-sdk.sh
  - git clone --depth 1 -b "master" --single-branch https://github.com/shivanshs9/kind-travis-ci.git
  - ./kind-travis-ci/kind/k8s-create.sh -sc

script:
  - . ./env.sh
  - ./build.sh
  - kind load docker-image "$OP_IMAGE"
  - ./deploy/qserv.sh --dev --install-kubedb
  - kubectl apply -k overlays/ci-redis
  - ./wait-qserv-ready.sh
  - kubectl get all,endpoints,cm,pvc,pv -o wide
  - ./run-integration-tests.sh

after_success:
  - echo "Generate and upload documentation"
  - curl -fsSL https://raw.githubusercontent.com/lsst/doc-container/tickets\/DM-23256/run.sh | bash -s -- -p "$LTD_PASSWORD" "$PWD"
